### PR TITLE
Portfolio Chart Styling (Work in progress)

### PR DESCRIPTION
**Pull request by swansobp**
Added a label, and began trying to remove the white background of the chart, was able to change part of it but still working on making it look good

### CODE REVIEW

**Review by nickclason — COMMENTED** [review]
in _stock-info.component.ts_, technically you are right marking the null values with "!" to promise that they will have values, but we can also set in _tsconfig.json:_

angularCompilerOptions: {"strictPropertyInitialization": false} 

and this will stop the compiler from throwing errors when defining variables with no value.

**Comment by swansobp** [comment]
I made that change at one point earlier but had some weird issue where I wasn't allowed to save the json file, but yeah I know what you mean, feel free to undo that change

**Comment by nickclason** [comment]
It doesn't hurt so its fine.

**Review by nickclason — APPROVED** [review]
Looks fine to me. Weird border around the chart when you add the title property. I also saw that, I think you might be able to hide it with css. But I know you said its not done yet

**Pull request merged**
